printWidth: 120
trailingComma: all
useTabs: false
tabWidth: 4
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
bracketSameLine: true
bracketSpacing: true
arrowParens: always
htmlWhitespaceSensitivity: strict
endOfLine: auto
overrides:
  - files: '*.yml'
    options:
      tabWidth: 2
